// authentication
export const FETCH_AUTH = 'FETCH_AUTH'
export const FETCH_LOGGED_USER = 'FETCH_LOGGED_USER'
// sign in/out
export const LOGIN_USER = 'LOGIN_USER'
export const GET_LOGIN_EMAIL = 'GET_LOGIN_EMAIL'
export const GET_LOGIN_PASSWORD ='GET_LOGIN_PASSWORD'
export const LOGOUT_USER = 'LOGOUT_USER'
// follower's sign up
export const REGISTER_USER = 'REGISTER_USER'
export const GET_REGISTER_FIRSTNAME = 'GET_REGISTER_FIRSTNAME'
export const GET_REGISTER_USERNAME = 'GET_REGISTER_USERNAME'
export const GET_REGISTER_EMAIL = 'GET_REGISTER_EMAIL'
export const GET_REGISTER_PASSWORD = 'GET_REGISTER_PASSWORD'
export const GET_REGISTER_PASSWORD_MATCH = 'GET_REGISTER_PASSWORD_MATCH'
// creator's sign up
export const REGISTER_CREATOR = 'REGISTER_CREATOR'
export const GET_CREATOR_REGISTER_NAMEDISPLAYED = 'GET_CREATOR_REGISTER_NAMEDISPLAYED'
export const GET_CREATOR_REGISTER_USERNAME = 'GET_CREATOR_REGISTER_USERNAME'
export const GET_CREATOR_REGISTER_EMAIL = 'GET_CREATOR_REGISTER_EMAIL'
export const GET_CREATOR_REGISTER_PASSWORD = 'GET_CREATOR_REGISTER_PASSWORD'
export const GET_CREATOR_REGISTER_PASSWORD_MATCH = 'GET_CREATOR_REGISTER_PASSWORD_MATCH'
// merging
export const FETCH_MERGING = 'FETCH_MERGING'
export const UPDATE_TAG = 'UPDATE_TAG'
// settings personal
export const SETTINGS_HYDRATE_INITIAL = 'SETTINGS_HYDRATE_INITIAL'
export const SETTINGS_PERSONAL_UPDATE_NAME = 'SETTINGS_PERSONAL_UPDATE_NAME'
export const SETTINGS_PERSONAL_UPDATE_USERNAME = 'SETTINGS_PERSONAL_UPDATE_USERNAME'
export const SETTINGS_PERSONAL_UPDATE_EMAIL = 'SETTINGS_PERSONAL_UPDATE_EMAIL'
export const SETTINGS_PERSONAL_UPDATE_ABOUT = 'SETTINGS_PERSONAL_UDPATE_ABOUT'
export const SETTINGS_PERSONAL_SUCCESS = 'SETTINGS_PERSONAL_SUCCESS'
// lists
export const FETCH_CREATORS = 'FETCH_CREATORS'
// explore
export const LOAD_CREATORS_CHUNK = 'LOAD_CREATORS_CHUNK'
export const TRIGGER_USER_FOLLOW = 'TRIGGER_USER_FOLLOW'
export const TRIGGER_REFRESH_EXPLORE = 'TRIGGER_REFRESH_EXPLORE'
// ocean
export const FETCH_FULL_OCEAN = 'FETCH_FULL_OCEAN'
export const LOAD_OCEAN_CHUNK = 'LOAD_OCEAN_CHUNK'
export const CLEAR_OCEAN = 'CLEAR_OCEAN'
export const TRIGGER_REFRESH_HOME = 'TRIGGER_REFRESH_HOME'
// home user
export const FETCH_HOME_PATH_USER = 'FETCH_HOME_PATH_USER'
export const FETCH_HOME_FULL_RIVER = 'FETCH_HOME_FULL_RIVER'
export const LOAD_HOME_RIVER_CHUNK = 'LOAD_HOME_RIVER_CHUNK'
export const TRIGGER_HOME_USER_FOLLOW = 'TRIGGER_HOME_USER_FOLLOW'
export const TRIGGER_REFRESH_HOME_PROFILE = 'TRIGGER_REFRESH_HOME_PROFILE'
// explore user
export const FETCH_EXPLORE_PATH_USER = 'FETCH_EXPLORE_PATH_USER'
export const FETCH_EXPLORE_FULL_RIVER = 'FETCH_EXPLORE_FULL_RIVER'
export const LOAD_EXPLORE_RIVER_CHUNK = 'LOAD_EXPLORE_RIVER_CHUNK'
export const TRIGGER_EXPLORE_USER_FOLLOW = 'TRIGGER_EXPLORE_USER_FOLLOW'
export const TRIGGER_REFRESH_EXPLORE_PROFILE = 'TRIGGER_REFRESH_EXPLORE_PROFILE'
// logged user
export const FETCH_LOGGED_PATH_USER = 'FETCH_LOGGED_PATH_USER'
export const FETCH_LOGGED_FULL_RIVER = 'FETCH_LOGGED_FULL_RIVER'
export const LOAD_LOGGED_RIVER_CHUNK = 'LOAD_LOGGED_RIVER_CHUNK'
export const TRIGGER_REFRESH_LOGGED_PROFILE = 'TRIGGER_REFRESH_LOGGED_PROFILE'
