// authentication
export const FETCH_AUTH = 'FETCH_AUTH'
export const FETCH_LOGGED_USER = 'FETCH_LOGGED_USER'
// sign in/out
export const LOGIN_USER = 'LOGIN_USER'
export const GET_LOGIN_EMAIL = 'GET_LOGIN_EMAIL'
export const GET_LOGIN_PASSWORD ='GET_LOGIN_PASSWORD'
// follower's sign up
export const REGISTER_USER = 'REGISTER_USER'
export const GET_REGISTER_FIRSTNAME = 'GET_REGISTER_FIRSTNAME'
export const GET_REGISTER_USERNAME = 'GET_REGISTER_USERNAME'
export const GET_REGISTER_EMAIL = 'GET_REGISTER_EMAIL'
export const GET_REGISTER_PASSWORD = 'GET_REGISTER_PASSWORD'
export const GET_REGISTER_PASSWORD_MATCH = 'GET_REGISTER_PASSWORD_MATCH'
// creator's sign up
export const REGISTER_CREATOR = 'REGISTER_CREATOR'
export const GET_CREATOR_REGISTER_NAMEDISPLAYED = 'GET_CREATOR_REGISTER_NAMEDISPLAYED'
export const GET_CREATOR_REGISTER_USERNAME = 'GET_CREATOR_REGISTER_USERNAME'
export const GET_CREATOR_REGISTER_EMAIL = 'GET_CREATOR_REGISTER_EMAIL'
export const GET_CREATOR_REGISTER_PASSWORD = 'GET_CREATOR_REGISTER_PASSWORD'
export const GET_CREATOR_REGISTER_PASSWORD_MATCH = 'GET_CREATOR_REGISTER_PASSWORD_MATCH'
// settings personal
export const SETTINGS_HYDRATE_INITIAL = 'SETTINGS_HYDRATE_INITIAL'
export const SETTINGS_PERSONAL_UPDATE_NAME = 'SETTINGS_PERSONAL_UPDATE_NAME'
export const SETTINGS_PERSONAL_UPDATE_USERNAME = 'SETTINGS_PERSONAL_UPDATE_USERNAME'
export const SETTINGS_PERSONAL_UPDATE_EMAIL = 'SETTINGS_PERSONAL_UPDATE_EMAIL'
export const SETTINGS_PERSONAL_UPDATE_ABOUT = 'SETTINGS_PERSONAL_UDPATE_ABOUT'
export const SETTINGS_PERSONAL_SUCCESS = 'SETTINGS_PERSONAL_SUCCESS'
